### ISSUE TITLE
Error flash Arduino Firmware

### ISSUE THREAD

**Issue by matko93** [brewpi-remix/brewpi-tools-rmx#30]
I installed a clean version of Brewpi and when I try to flash the firmware on the Arduino I get this error:
sudo /home/brewpi/utils/updateFirmware.py

Stopping this chamber's instance(s) of BrewPi to check/update controller.

Stopping BrewPi with PID 848.

Checking current firmware version.
Opening serial port.
Traceback (most recent call last):
File "/home/brewpi/utils/updateFirmware.py", line 126, in updateFromGitHub
family = hwVersion.family
AttributeError: 'NoneType' object has no attribute 'family'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/brewpi/utils/updateFirmware.py", line 420, in
result = main()
File "/home/brewpi/utils/updateFirmware.py", line 415, in main
result = updateFromGitHub(beta, doShield, userInput)
File "/home/brewpi/utils/updateFirmware.py", line 135, in updateFromGitHub
"\nunresponsive, or if this is a new controller you can choose to proceed" +
File "/home/brewpi/utils/updateFirmware.py", line 56, in pipeInput
result = raw_input(prompt)
NameError: name 'raw_input' is not defined

**Comment by lbussy** [comment]
Is this a real Uno, or a knock off?

--
Lee Bussy

**Comment by matko93** [comment]
It was Arduino UNO revC. Is there any other method for flash firmware?

**Comment by asnyder91** [comment]
Similar issue. Automated brewpi install failed at arduino flash step (no error shown, the prompt went away too quickly). Tried manual install using updateFirmware.py command. Error output below.

NOTE: I had another brewpi with Version 0.5.3.1 on it and this version was able to flash my (real) arduino uno just fine with revc using the same updateFirmware.py command.

Here is the 0.5.4.0 brewpi output of the sudo /home/brewpi/utils/updateFirmware.py command:
`pi@raspberrypi:~ $ sudo /home/brewpi/utils/updateFirmware.py

Stopping this chamber's instance(s) of BrewPi to check/update controller.

Stopping BrewPi with PID 1419.

Checking current firmware version.
Opening serial port.

Found the following controller:
BrewPi v0.2.12 build 8d36524, running on an Arduino Uno with a revC shield
on port /dev/ttyACM0.

Current firmware version on controller: 0.2.12

Checking GitHub for available release(s).
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brewpi/utils/updateFirmware.py", line 420, in <module>
    result = main()
  File "/home/brewpi/utils/updateFirmware.py", line 415, in main
    result = updateFromGitHub(beta, doShield, userInput)
  File "/home/brewpi/utils/updateFirmware.py", line 206, in updateFromGitHub
    releases = gitHubReleases(firmRepo)
  File "/home/brewpi/utils/gitHubReleases.py", line 52, in __init__
    self.update()
  File "/home/brewpi/utils/gitHubReleases.py", line 95, in update
    self.releases = json.loads(urlopen(self.url + "/releases").read().decode('utf-8'))
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
`

I hope this helps lbussy!
Thanks!

**Comment by lbussy** [comment]
Interesting.  Okay I have an appointment this afternoon but I should be able to look in a couple hours.
