### ISSUE TITLE
Failed to retrieve Tilt value, restarting Tilt.

### ISSUE THREAD

**Issue by CodeAndKegs** [brewpi-remix/brewpi-tools-rmx#72]
Doing a clean install on a fresh Pi4

Ran through the installation with no issues.  Selected Blue Tilt during set up, and noticed no hydrometer data was available and the following errors in stderr:

>2024-11-23 14:27:54 [E] Starting BrewPi.
>/home/brewpi/Tilt.py:328: RuntimeWarning: coroutine 'BLEScanRequester.send_scan_request' was never awaited self.btctrl.send_scan_request()
>RuntimeWarning: Enable tracemalloc to get the object allocation traceback
>/home/brewpi/brewpi.py:751: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  if LooseVersion(hwVersion.toString()) < LooseVersion(compatibleHwVersion):
>2024-11-23 14:28:05 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>/home/brewpi/Tilt.py:343: RuntimeWarning: coroutine 'BLEScanRequester.stop_scan_request' was never awaited  self.btctrl.stop_scan_request()
>RuntimeWarning: Enable tracemalloc to get the object allocation traceback
>/home/brewpi/Tilt.py:345: RuntimeWarning: coroutine 'BLEScanRequester.send_command' was never awaited self.btctrl.send_command(command)
>RuntimeWarning: Enable tracemalloc to get the object allocation traceback
>2024-11-23 14:28:05 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>2024-11-23 14:28:58 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>2024-11-23 14:28:58 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>2024-11-23 14:30:59 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>2024-11-23 14:33:00 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>2024-11-23 14:35:01 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>2024-11-23 14:37:02 [E] Failed to retrieve Blue Tilt value, restarting Tilt.
>...

Interesting thing is as I went to follow the directions to install Tilt Pi independently data starting showing up.  I followed the following steps from the Tilt website:
>wget https://github.com/baronbrew/aioblescan/archive/master.zip
>unzip master.zip
>cd aioblescan-master/
>sudo -H python3 setup.py install

And when I did 
>sudo python3 -u -m aioblescan -T

to verify Tilt scanner is working, data started appearing on the brewpi dashboard.

I would leave well enough alone, except whenever I go to stop the script, everything hangs after:
>Traceback (most recent call last):
>  File "/home/brewpi/brewpi.py", line 1891, in <module>
>    main()
>  File "/home/brewpi/brewpi.py", line 1885, in main
>    shutdown()  # Process graceful shutdown
>    ^^^^^^^^^^
>  File "/home/brewpi/brewpi.py", line 1837, in shutdown
>    tilt.stop()
>  File "/home/brewpi/Tilt.py", line 346, in stop
>    asyncio.gather(*asyncio.Task.all_tasks()).cancel()
>                    ^^^^^^^^^^^^^^^^^^^^^^
>AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

Thank you so much for maintaining!

**Comment by lbussy** [comment]
Well, that's interesting.  That you had an issue was not a huge surprise, I need to freshen things up.  I am glad the Tilt guys seem to have kept a stripped down version available, it's a place to start. 

I have NO idea where my tilt is, I've been full time in a RV for a couple years, but I can have a look and see if I can stop the errors, maybe that will be a quick fix.

**Comment by CodeAndKegs** [comment]
okay, so I updated one line in Tilt.py tiltManager start and a few lines in stop and it seems to be working just fine.

In start, I switched:
>self.btctrl.send_scan_request()

for
>asyncio.run_coroutine_threadsafe(self.btctrl.send_scan_request(), self.event_loop)

I updated stop to be:

>     def stop(self):
>         """
>         Stop the BLE scanning thread
> 
>         :return: None
>         """
> 
>        # self.btctrl.stop_scan_request()
>        stop_task = asyncio.run_coroutine_threadsafe(self.btctrl.stop_scan_request(), self.event_loop)
>        stop_task.result()
>        command = aioblescan.HCI_Cmd_LE_Advertise(enable=False)
>        #self.btctrl.send_command(command)
>        send_task = asyncio.run_coroutine_threadsafe(self.btctrl.send_command(command), self.event_loop)
>        send_task.result()
>        #asyncio.gather(*asyncio.Task.all_tasks()).cancel()
>        tasks = asyncio.all_tasks(self.event_loop)
>        for task in tasks:
>            task.cancel()
>            try:
>                self.event_loop.run_until_complete(task)
>            except asyncio.CancelledError:
>                pass

I also updated brewpi.py 
```
#from distutils.version import LooseVersion
from packaging.version import parse

```
and later:

```
            #if LooseVersion(hwVersion.toString()) < LooseVersion(compatibleHwVersion):
            if parse(hwVersion.toString()) < parse(compatibleHwVersion):
```

So far, everything seems to be working (start/stop script, Tilt values appear without additional commands), hope you can validate this doesn't impact anything else and I'll let you know if anything breaks in the meantime.

**Comment by lbussy** [comment]
Thank you for this!

Not sure I can validate as my test rigs are "somewhere" but I'll have a look.

**Comment by lbussy** [comment]
Adding a note here for myself, repo is here:  https://github.com/baronbrew/aioblescan/

**Comment by lbussy** [comment]
Leaving myself another note, the upstream from Tilt may be viable:

https://github.com/frawau/aioblescan/compare/0.2.4...0.2.14
